## **Studi Kasus 1**
### **Project Klasifikasi Sentimen Analisis**
---

### Sentimen Analisis Video Review Makanan di Youtube

In [1]:
!pip install google-api-python-client

In [2]:
#library yang digunakan, jika dirasa kurang penting dapat dihapus
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import string
import re
from nltk import word_tokenize
import nltk
nltk.download('punkt')
nltk.download('stopwords')
from nltk.corpus import stopwords
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from wordcloud import WordCloud, STOPWORDS
from sklearn.metrics import ConfusionMatrixDisplay
from textblob import TextBlob
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Acer\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Acer\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [3]:
# Call the "build()" function from the Python-client
from googleapiclient.discovery import build

api_key = "AIzaSyA7BDBeQUxMoe98wAoh9ThWVjxocWARf54" 
youtube = build("youtube", "v3", developerKey=api_key)
url = "https://www.youtube.com/watch?v=VkmQ5BgkeD0"  


def get_comments(url):
    # Get the ID of the video by splitting the URL
    single_video_id = url.split("=")[1].split("&")[0]
    # Use the list() method to extract a JSON with key information
    # from the video.
    video_list=youtube.videos().list(part="snippet",id=single_video_id).execute()
    channel_id= video_list["items"][0]["snippet"]["channelId"]
    title_single_video= video_list["items"][0]["snippet"]["title"]
    playlist_id = None
    forUserName = None

    nextPageToken_comments = None
    commentsone=[]

    while True:
        #Request the first 50 videos of a channel. This is the full dictionary. The result is store in a variable called "pl_response".
        #PageToken at this point is "None"
        pl_request_comment= youtube.commentThreads().list(part=["snippet","replies"],
                                            videoId=single_video_id,
                                            maxResults=50,
                                            pageToken= nextPageToken_comments)
        pl_response_comment = pl_request_comment.execute()

        ## Send the amount of views and the URL of each video to the videos empty list that was declared at the beginning of the code.
        for i in pl_response_comment["items"]:
            vid_comments = i["snippet"]["topLevelComment"]["snippet"]["textOriginal"]
            comm_author = i["snippet"]["topLevelComment"]["snippet"]["authorDisplayName"]
            comm_author_id = i["snippet"]["topLevelComment"]["snippet"]["authorChannelId"]["value"]
            comm_date = i["snippet"]["topLevelComment"]["snippet"]["publishedAt"]
            comm_likes = i["snippet"]["topLevelComment"]["snippet"]["likeCount"]
            new_var=i.get("replies","0")

            commentsone.append({
                "comm_date":comm_date,
                "author":comm_author,
                "author_id":comm_author_id,
                "likes":comm_likes,
                "comment":vid_comments,
                "video_id":single_video_id
            })



        nextPageToken_comments = pl_response_comment.get("nextPageToken")

        if not nextPageToken_comments:
            break

    for i in commentsone[:10]:
        print(i["comment"])


    pd.DataFrame.from_dict(commentsone).to_csv(f"dataset.csv")

get_comments(url)

Guys untuk kiting cake ada kesalahan penulisan harga yaa.. harusnya harganya 195.000 bukan 360.000

Mohon Maaf atas kesalahan penulisanyaa

🙏🏻🙏🏻
24:06 bejir jastipnya markupnya banyak buanget wkwkwkwk pdhl sama sama jkt😅 btw ada yg bahannya kek donbakeshop baru launching, circles bakery
15:27 donbakeshop ni wkwkwk keliatan beet. Dia pake seasalt kak di dalemnya pistachio+ktaifi wkwk
8:21 dari sini keliatan jelas fix yg ini wkwk
battle basreng mentah kak
Malah iklan skincare
Klau lumer memang pistachio bakalan kurang berasa lah, kan banyakan cairannya (oil), klau mau berasa pistachio ya cairan (oilnya) dibuat sedikit, tp jd kering ngga lumer
Beli yg by chi keik dmna ya?
No 10 apa ee penisirin 😅
battle nugget


In [4]:
df = pd.read_csv('dataset.csv')
df.head(500)

Unnamed: 0             comm_date                       author  \
0             0  2024-11-21T19:23:53Z               @TasyiAthasyia   
1             1  2024-12-04T12:37:18Z                  @cupidkid97   
2             2  2024-12-04T12:29:24Z                  @cupidkid97   
3             3  2024-12-04T12:18:05Z                  @cupidkid97   
4             4  2024-12-04T12:02:45Z          @devitaparamita5429   
..          ...                   ...                          ...   
495         495  2024-11-21T16:50:59Z           @shintawidjaya7963   
496         496  2024-11-21T16:46:20Z              @elzioputra9823   
497         497  2024-11-21T16:36:11Z          @HamzahSulaiman-z4n   
498         498  2024-11-21T16:34:06Z  @fathimahbasyafofficial2340   
499         499  2024-11-21T16:30:35Z               @anitasofia400   

                    author_id  likes  \
0    UC3rBdOAdLXhagcFtEnSAmQQ    914   
1    UCktPq1Ixtp3lvMziiv39vcQ      0   
2    UCktPq1Ixtp3lvMziiv39vcQ      0   
3    UCktPq1Ixtp3lvMziiv39vcQ      0   
4    UCcRW2Xll4-4-ZQnZQW7R2Zw      1   
..                        ...    ...   
495  UCw8lHcliYRuWaLKemuwWA8w      0   
496  UCQmNCWb4T09x-KDvx0HAbxA      0   
497  UCCxMfpAYmKzcJxA6_kypbdA      0   
498  UC_bdv6Jz6pU80nNmnCoRzjg      0   
499  UCINdDdxx5syFtY34M1UhBkA      0   

                                               comment     video_id  
0    Guys untuk kiting cake ada kesalahan penulisan...  VkmQ5BgkeD0  
1    24:06 bejir jastipnya markupnya banyak buanget...  VkmQ5BgkeD0  
2    15:27 donbakeshop ni wkwkwk keliatan beet. Dia...  VkmQ5BgkeD0  
3        8:21 dari sini keliatan jelas fix yg ini wkwk  VkmQ5BgkeD0  
4                            battle basreng mentah kak  VkmQ5BgkeD0  
..                                                 ...          ...  
495            kaa battle dark/milk coklat lokal dongg  VkmQ5BgkeD0  
496                                         We made it  VkmQ5BgkeD0  
497  sumpah 1 selera sama tasyi banget parah, donba...  VkmQ5BgkeD0  
498  Congrats k tasyiii dah trending satu aja video...  VkmQ5BgkeD0  
499                                         WE MADE IT  VkmQ5BgkeD0  

[500 rows x 7 columns]

In [5]:
df.count()

Unnamed: 0    836
comm_date     836
author        836
author_id     836
likes         836
comment       836
video_id      836
dtype: int64

In [6]:
df = df.dropna()

In [7]:
data_nw = df.drop(['comm_date',"author", 'author_id',"likes",'video_id'], axis=1 )
data_nw

Unnamed: 0                                            comment
0             0  Guys untuk kiting cake ada kesalahan penulisan...
1             1  24:06 bejir jastipnya markupnya banyak buanget...
2             2  15:27 donbakeshop ni wkwkwk keliatan beet. Dia...
3             3      8:21 dari sini keliatan jelas fix yg ini wkwk
4             4                          battle basreng mentah kak
..          ...                                                ...
831         831                                              First
832         832                                              Wuihh
833         833                                              First
834         834           AKHIRNYAAAA BATTLE YANG DI TUNGGU-TUNGGU
835         835         pertamaaa, seneng bgt dpt notif battle❤❤❤❤

[836 rows x 2 columns]

In [8]:
data_nw.to_csv("dataset/dataset_drop.csv") #Fungsinya untuk menyimpan hasil drop

In [9]:
data_baru = pd.read_csv("dataset/dataset_drop.csv")
data_baru.head()

Unnamed: 0.1  Unnamed: 0                                            comment
0             0           0  Guys untuk kiting cake ada kesalahan penulisan...
1             1           1  24:06 bejir jastipnya markupnya banyak buanget...
2             2           2  15:27 donbakeshop ni wkwkwk keliatan beet. Dia...
3             3           3      8:21 dari sini keliatan jelas fix yg ini wkwk
4             4           4                          battle basreng mentah kak

In [10]:
def caseFolding(comment):
          comment = comment.lower()
          comment = comment.strip(" ")
          comment = re.sub(r'[?|$|.|!]',r'', comment)
          comment = re.sub(r'[^a-zA-Z0-9 ]',r'', comment)
          return comment

data_baru['comment'] = data_baru['comment'].apply(caseFolding)

In [11]:
data_baru.to_csv("dataset_bersih.csv")

In [12]:
dataset_baru = pd.read_csv('dataset_bersih.csv')

# Mengisi nilai NaN dengan string kosong
dataset_baru['comment'] = dataset_baru['comment'].fillna("")

# Semua Nilai Bertipe String
dataset_baru['comment'] = dataset_baru['comment'].astype(str)

In [13]:
dataset_baru = list(dataset_baru['comment'])

# Inisialisasi variabel
polaritas = 0
status = []
total_positif = total_negatif = total_netral = total = 0

# Analisis sentimen
for i, tweet in enumerate(dataset_baru):
    analysis = TextBlob(tweet)
    polaritas += analysis.polarity

    # Klasifikasi sentimen berdasarkan polaritas
    if analysis.sentiment.polarity > 0.0:
        total_positif += 1
        status.append('Positif')
    elif analysis.sentiment.polarity == 0.0:
        total_netral += 1
        status.append('Netral')
    else:
        total_negatif += 1
        status.append('Negatif')

    total += 1

# Menambahkan kolom 'sentimen' ke dataset asli
df['sentimen'] = status

# Menyimpan hasil ke file baru
df.to_csv('dataset_analisis_sentimen.csv', index=False)

# Output hasil analisis
print(f'Hasil Analisis Data:')
print(f'Positif = {total_positif}')
print(f'Netral = {total_netral}')
print(f'Negatif = {total_negatif}')
print(f'\nTotal Data : {total}')

Hasil Analisis Data:
Positif = 41
Netral = 790
Negatif = 5

Total Data : 836


In [17]:
data = pd.read_csv('dataset_analisis_sentimen.csv')
data.head()

Unnamed: 0             comm_date               author  \
0           0  2024-11-21T19:23:53Z       @TasyiAthasyia   
1           1  2024-12-04T12:37:18Z          @cupidkid97   
2           2  2024-12-04T12:29:24Z          @cupidkid97   
3           3  2024-12-04T12:18:05Z          @cupidkid97   
4           4  2024-12-04T12:02:45Z  @devitaparamita5429   

                  author_id  likes  \
0  UC3rBdOAdLXhagcFtEnSAmQQ    914   
1  UCktPq1Ixtp3lvMziiv39vcQ      0   
2  UCktPq1Ixtp3lvMziiv39vcQ      0   
3  UCktPq1Ixtp3lvMziiv39vcQ      0   
4  UCcRW2Xll4-4-ZQnZQW7R2Zw      1   

                                             comment     video_id sentimen  
0  Guys untuk kiting cake ada kesalahan penulisan...  VkmQ5BgkeD0   Netral  
1  24:06 bejir jastipnya markupnya banyak buanget...  VkmQ5BgkeD0   Netral  
2  15:27 donbakeshop ni wkwkwk keliatan beet. Dia...  VkmQ5BgkeD0   Netral  
3      8:21 dari sini keliatan jelas fix yg ini wkwk  VkmQ5BgkeD0   Netral  
4                          battle basreng mentah kak  VkmQ5BgkeD0   Netral

In [18]:
X = data['comment']
y = data['sentimen']

In [20]:
# Lakukan preprocessing pada teks
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

nltk.download('stopwords')

def preprocessing(text):
    text = text.lower()
    text = re.sub(r'\d+', '', text)
    text = re.sub(r'[^\w\s]', '', text)
    text = text.strip()
    tokens = nltk.word_tokenize(text)
    stop_words = set(stopwords.words('indonesian'))
    filtered_tokens = [token for token in tokens if token not in stop_words]
    stemmer = PorterStemmer()
    stemmed_tokens = [stemmer.stem(token) for token in filtered_tokens]
    return ' '.join(stemmed_tokens)

X = X.apply(preprocessing)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Acer\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [21]:
# Lakukan vectorization pada teks
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(X)

In [22]:
# Lakukan pembagian dataset menjadi data training dan data testing
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [23]:
# Lakukan training model KNN
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [24]:
# Lakukan prediksi pada data testing
y_pred = knn.predict(X_test)

In [25]:
# Lakukan evaluasi model
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')
cm = confusion_matrix(y_test, y_pred)

print('Accuracy:', accuracy)
print('Precision:', precision)
print('Recall:', recall)
print('F1 Score:', f1)
print('Confusion Matrix:\n', cm)

Accuracy: 0.9285714285714286
Precision: 0.9277516395779868
Recall: 0.9285714285714286
F1 Score: 0.8992247400632494
Confusion Matrix:
 [[  0   1   0]
 [  0 155   0]
 [  0  11   1]]


C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
